import fs from "fs";
import path from "path";

export interface ProcessStage {
    stageName: string;
    date: string;
    children?: {
        stageName: string;
        date: string;
        decision?: string;
    }[];
}

export interface Bill {
    id: string;
    eli: string;
    title: string;
    description: string;
    documentType: string;
    authorType: string;
    isapLink?: string;
    eliLink?: string;
    rclLink?: string;
    rclProjectId?: string;
    kanbanStage?: string;
    isEU: boolean;
    date: string;
    term: number;
    urgency: string;
    stages: ProcessStage[];
}

export async function getBills(): Promise<Bill[]> {
    try {
        // Point to the correct file generated by backend/fetch_bills.py
        const filePath = path.join(process.cwd(), 'public/data/bills.json');
        if (fs.existsSync(filePath)) {
            const fileContent = fs.readFileSync(filePath, 'utf-8');
            const data = JSON.parse(fileContent);

            // Ensure stages array exists even if missing in JSON
            return data.map((item: any) => ({
                ...item,
                stages: item.stages || []
            }));
        }
    } catch (e) {
        console.warn("Processes data not found", e);
    }
    return [];
}

export async function getBill(id: string): Promise<Bill | undefined> {
    try {
        // 1. Get summary to have the Kanban stage and other computed fields
        const allBills = await getBills();
        const summary = allBills.find(p => p.id === id);

        // 2. Get detailed data for stages
        const detailPath = path.join(process.cwd(), `public/data/bills/${id}.json`);
        let details: any = {};

        if (fs.existsSync(detailPath)) {
            const detailContent = fs.readFileSync(detailPath, 'utf-8');
            details = JSON.parse(detailContent);
        }

        if (!summary && !details.id) return undefined;

        // 3. Merge
        // Summary has better computed fields (kanbanStage), Details has 'stages' array
        return {
            ...(summary || {} as Bill),
            ...details,
            // Ensure we keep the computed fields from summary if details are missing them
            kanbanStage: summary?.kanbanStage || details.kanbanStage,
            id: id,
            // Stages come from details
            stages: details.stages || []
        };

    } catch (e) {
        console.warn(`Error fetching bill ${id}`, e);
        return undefined;
    }
}
