import fs from "fs";
import path from "path";

export interface ProcessStage {
    stageName: string;
    date: string;
    children?: {
        stageName: string;
        date: string;
        decision?: string;
    }[];
}

export interface LegislativeProcess {
    id: string;
    eli: string;
    title: string;
    description: string;
    documentType: string;
    isEU: boolean;
    date: string;
    term: number;
    urgency: string;
    stages: ProcessStage[];
    kanbanStage?: string; // Added field
    isapLink?: string;
    eliLink?: string;
}

export async function getProcesses(): Promise<LegislativeProcess[]> {
    try {
        // Point to the correct file generated by backend/fetch_bills.py
        const filePath = path.join(process.cwd(), 'lib/bills_data.json');
        if (fs.existsSync(filePath)) {
            const fileContent = fs.readFileSync(filePath, 'utf-8');
            const data = JSON.parse(fileContent);

            // Ensure stages array exists even if missing in JSON
            return data.map((item: any) => ({
                ...item,
                stages: item.stages || []
            }));
        }
    } catch (e) {
        console.warn("Processes data not found", e);
    }
    return [];
}

export async function getProcess(id: string): Promise<LegislativeProcess | undefined> {
    const processes = await getProcesses();
    return processes.find(p => p.id === id);
}
